#include <pow/opencl_miner.h>
#include <pow/tknchash.h>
#include <pow/cn_slow_hash.hpp>
#include <pow/real_gpu_miner.h>
#include <util/log.h>
#include <arith_uint256.h>
#include <uint256.h>
#include <primitives/block.h>
#include <streams.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-function-type"
#endif

// Embedded OpenCL kernel (compile-time fallback, zero external dependency)
// Generated by cmake/embed_cl.cmake from pow/tokenhash.cl
#include <pow/tokenhash_cl.h>

#ifndef SER_NETWORK
#define SER_NETWORK 0
#endif
#ifndef PROTOCOL_VERSION
#define PROTOCOL_VERSION 70016
#endif

#ifdef __APPLE__
#include <mach-o/dyld.h>
#include <dlfcn.h>
#endif

#ifdef __linux__
#include <unistd.h>
#endif

#include <chrono>
#include <cinttypes>
#include <fstream>
#include <sstream>
#include <vector>
#include <cstring>
#include <algorithm>
#include <thread>
#include <mutex>

#ifdef _WIN32
#include <windows.h>
#endif

static const uint64_t TKNCHASH_ITERATIONS = 768;
static const uint64_t TKNCHASH_MEMORY = 32 * 1024;
static const uint64_t TKNCHASH_MASK = ((TKNCHASH_MEMORY - 1) >> 6) << 6;
static const uint32_t TKNCHASH_NONCE_LEN = 4;
static const int TKNCHASH_WORKSIZE = 8;
static const int TKNCHASH_COMP_MODE = 1;
static const int TKNCHASH_CN_UNROLL = 1;

std::atomic<bool> OpenCLMiner::s_initialized{false};
std::atomic<bool> OpenCLMiner::s_available{false};
std::string OpenCLMiner::s_device_name = "None";
std::atomic<float> OpenCLMiner::s_gpu_utilization{0.0f};
std::atomic<uint64_t> OpenCLMiner::s_total_hashes{0};

#ifdef _WIN32
static HMODULE s_opencl_dll = nullptr;
#endif

static fn_clGetPlatformIDs pfn_clGetPlatformIDs = nullptr;
static fn_clGetPlatformInfo pfn_clGetPlatformInfo = nullptr;
static fn_clGetDeviceIDs pfn_clGetDeviceIDs = nullptr;
static fn_clCreateContext pfn_clCreateContext = nullptr;
static fn_clCreateCommandQueue pfn_clCreateCommandQueue = nullptr;
static fn_clCreateProgramWithSource pfn_clCreateProgramWithSource = nullptr;
static fn_clBuildProgram pfn_clBuildProgram = nullptr;
static fn_clCreateKernel pfn_clCreateKernel = nullptr;
static fn_clCreateBuffer pfn_clCreateBuffer = nullptr;
static fn_clEnqueueWriteBuffer pfn_clEnqueueWriteBuffer = nullptr;
static fn_clSetKernelArg pfn_clSetKernelArg = nullptr;
static fn_clEnqueueNDRangeKernel pfn_clEnqueueNDRangeKernel = nullptr;
static fn_clEnqueueReadBuffer pfn_clEnqueueReadBuffer = nullptr;
static fn_clReleaseMemObject pfn_clReleaseMemObject = nullptr;
static fn_clReleaseKernel pfn_clReleaseKernel = nullptr;
static fn_clReleaseProgram pfn_clReleaseProgram = nullptr;
static fn_clReleaseCommandQueue pfn_clReleaseCommandQueue = nullptr;
static fn_clReleaseContext pfn_clReleaseContext = nullptr;
static fn_clGetDeviceInfo pfn_clGetDeviceInfo = nullptr;
static fn_clGetProgramBuildInfo pfn_clGetProgramBuildInfo = nullptr;
static fn_clGetEventProfilingInfo pfn_clGetEventProfilingInfo = nullptr;
static fn_clReleaseEvent pfn_clReleaseEvent = nullptr;

// Per-GPU worker: context, queue, kernels, buffers, and nonce range.
struct GPUWorker {
    cl_device_id device = nullptr;
    cl_platform_id platform = nullptr;
    cl_context context = nullptr;
    cl_command_queue queue = nullptr;
    cl_program program = nullptr;
    cl_kernel kernel_cn0 = nullptr;
    cl_kernel kernel_cn00 = nullptr;
    cl_kernel kernel_cn1 = nullptr;
    cl_kernel kernel_cn2 = nullptr;
    cl_mem input_buf = nullptr;
    cl_mem scratchpads_buf = nullptr;
    cl_mem states_buf = nullptr;
    cl_mem output_buf = nullptr;
    uint64_t max_threads = 0;
    int worksize = 1;
    std::string name;
    // Per-worker job state
    bool job_set = false;
    bool kernel_args_set = false;
    cl_ulong job_target_u64 = 0;
    uint32_t job_num_threads = 0;
    uint8_t last_input_data[128] = {0};
};

static std::vector<GPUWorker> s_workers;

static std::atomic<bool> s_cpu_mode{false};
static std::atomic<uint32_t> s_cpu_next_nonce{1};
static std::atomic<bool> s_block_found{false};
static std::atomic<uint32_t> s_found_nonce{0};

static uint64_t s_extra_nonce = 0;

static const int CPU_MINER_THREADS = 4;

#ifdef _WIN32
static thread_local bool s_seh_exception_occurred = false;

#ifdef _MSC_VER
// MSVC: Use SEH (Structured Exception Handling) for OpenCL calls

static int seh_call_clGetDeviceIDs(cl_platform_id platform, cl_device_type type, cl_uint count, cl_device_id* devices, cl_uint* out_count) {
 s_seh_exception_occurred = false;
 __try {
 return pfn_clGetDeviceIDs(platform, type, count, devices, out_count);
 } __except(EXCEPTION_EXECUTE_HANDLER) {
 s_seh_exception_occurred = true;
 return (int)GetExceptionCode();
 }
}

static int seh_call_clGetDeviceInfo(cl_device_id device, cl_uint param, size_t size, void* value, size_t* ret) {
 s_seh_exception_occurred = false;
 __try {
 return pfn_clGetDeviceInfo(device, param, size, value, ret);
 } __except(EXCEPTION_EXECUTE_HANDLER) {
 s_seh_exception_occurred = true;
 return (int)GetExceptionCode();
 }
}

static cl_context seh_call_clCreateContext(cl_context_properties* props, cl_uint num, cl_device_id* devs, void(*fn)(const char*, const void*, size_t, void*), void* data, cl_int* err) {
 s_seh_exception_occurred = false;
 __try {
 return pfn_clCreateContext(props, num, devs, fn, data, err);
 } __except(EXCEPTION_EXECUTE_HANDLER) {
 s_seh_exception_occurred = true;
 *err = (cl_int)GetExceptionCode();
 return nullptr;
 }
}

static cl_command_queue seh_call_clCreateCommandQueue(cl_context ctx, cl_device_id dev, cl_int props, cl_int* err) {
 s_seh_exception_occurred = false;
 __try {
 return pfn_clCreateCommandQueue(ctx, dev, props, err);
 } __except(EXCEPTION_EXECUTE_HANDLER) {
 s_seh_exception_occurred = true;
 *err = (cl_int)GetExceptionCode();
 return nullptr;
 }
}

static cl_program seh_call_clCreateProgramWithSource(cl_context ctx, cl_uint count, const char** strs, size_t* lens, cl_int* err) {
 s_seh_exception_occurred = false;
 __try {
 return pfn_clCreateProgramWithSource(ctx, count, strs, lens, err);
 } __except(EXCEPTION_EXECUTE_HANDLER) {
 s_seh_exception_occurred = true;
 *err = CL_OUT_OF_RESOURCES;
 return nullptr;
 }
}

static int seh_call_clBuildProgram(cl_program prog, cl_uint num, cl_device_id* devs, const char* opts) {
 s_seh_exception_occurred = false;
 __try {
 return pfn_clBuildProgram(prog, num, devs, opts, nullptr, nullptr);
 } __except(EXCEPTION_EXECUTE_HANDLER) {
 s_seh_exception_occurred = true;
 return CL_BUILD_ERROR;
 }
}

#else // MinGW GCC: Direct calls (no SEH support)

static int seh_call_clGetDeviceIDs(cl_platform_id platform, cl_device_type type, cl_uint count, cl_device_id* devices, cl_uint* out_count) {
 s_seh_exception_occurred = false;
 return pfn_clGetDeviceIDs(platform, type, count, devices, out_count);
}

static int seh_call_clGetDeviceInfo(cl_device_id device, cl_uint param, size_t size, void* value, size_t* ret) {
 s_seh_exception_occurred = false;
 return pfn_clGetDeviceInfo(device, param, size, value, ret);
}

static cl_context seh_call_clCreateContext(cl_context_properties* props, cl_uint num, cl_device_id* devs, void(*fn)(const char*, const void*, size_t, void*), void* data, cl_int* err) {
 s_seh_exception_occurred = false;
 return pfn_clCreateContext(props, num, devs, fn, data, err);
}

static cl_command_queue seh_call_clCreateCommandQueue(cl_context ctx, cl_device_id dev, cl_int props, cl_int* err) {
 s_seh_exception_occurred = false;
 return pfn_clCreateCommandQueue(ctx, dev, props, err);
}

static cl_program seh_call_clCreateProgramWithSource(cl_context ctx, cl_uint count, const char** strs, size_t* lens, cl_int* err) {
 s_seh_exception_occurred = false;
 return pfn_clCreateProgramWithSource(ctx, count, strs, lens, err);
}

static int seh_call_clBuildProgram(cl_program prog, cl_uint num, cl_device_id* devs, const char* opts) {
 s_seh_exception_occurred = false;
 return pfn_clBuildProgram(prog, num, devs, opts, nullptr, nullptr);
}

#endif // _MSC_VER / MinGW
#endif // _WIN32

bool OpenCLMiner::LoadOpenCLRuntime() {
#ifdef _WIN32
 s_opencl_dll = LoadLibraryA("OpenCL.dll");
 if (!s_opencl_dll) {
 LogError("tokenhash OpenCL: Failed to load OpenCL.dll");
 return false;
 }

 #define LOAD_FUNC(name) \
 pfn_##name = reinterpret_cast<fn_##name>(GetProcAddress(s_opencl_dll, #name)); \
 if (!pfn_##name) { LogError("tokenhash OpenCL: Cannot load " #name); return false; }

 LOAD_FUNC(clGetPlatformIDs)
 LOAD_FUNC(clGetPlatformInfo)
 LOAD_FUNC(clGetDeviceIDs)
 LOAD_FUNC(clCreateContext)
 LOAD_FUNC(clCreateCommandQueue)
 LOAD_FUNC(clCreateProgramWithSource)
 LOAD_FUNC(clBuildProgram)
 LOAD_FUNC(clCreateKernel)
 LOAD_FUNC(clCreateBuffer)
 LOAD_FUNC(clEnqueueWriteBuffer)
 LOAD_FUNC(clSetKernelArg)
 LOAD_FUNC(clEnqueueNDRangeKernel)
 LOAD_FUNC(clEnqueueReadBuffer)
 LOAD_FUNC(clReleaseMemObject)
 LOAD_FUNC(clReleaseKernel)
 LOAD_FUNC(clReleaseProgram)
 LOAD_FUNC(clReleaseCommandQueue)
 LOAD_FUNC(clReleaseContext)
 LOAD_FUNC(clGetDeviceInfo)
 LOAD_FUNC(clGetProgramBuildInfo)
 LOAD_FUNC(clGetEventProfilingInfo)
 LOAD_FUNC(clReleaseEvent)

 #undef LOAD_FUNC

 LogInfo("tokenhash OpenCL: Runtime loaded OK");
 return true;
#elif defined(__APPLE__)
 void* opencl_framework = dlopen("/System/Library/Frameworks/OpenCL.framework/OpenCL", RTLD_LAZY);
 if (!opencl_framework) {
 LogError("tokenhash OpenCL: Failed to load OpenCL.framework");
 return false;
 }

 #define LOAD_FUNC(name) \
 pfn_##name = reinterpret_cast<fn_##name>(dlsym(opencl_framework, #name)); \
 if (!pfn_##name) { LogError("tokenhash OpenCL: Cannot load " #name); return false; }

 LOAD_FUNC(clGetPlatformIDs)
 LOAD_FUNC(clGetPlatformInfo)
 LOAD_FUNC(clGetDeviceIDs)
 LOAD_FUNC(clCreateContext)
 LOAD_FUNC(clCreateCommandQueue)
 LOAD_FUNC(clCreateProgramWithSource)
 LOAD_FUNC(clBuildProgram)
 LOAD_FUNC(clCreateKernel)
 LOAD_FUNC(clCreateBuffer)
 LOAD_FUNC(clEnqueueWriteBuffer)
 LOAD_FUNC(clSetKernelArg)
 LOAD_FUNC(clEnqueueNDRangeKernel)
 LOAD_FUNC(clEnqueueReadBuffer)
 LOAD_FUNC(clReleaseMemObject)
 LOAD_FUNC(clReleaseKernel)
 LOAD_FUNC(clReleaseProgram)
 LOAD_FUNC(clReleaseCommandQueue)
 LOAD_FUNC(clReleaseContext)
 LOAD_FUNC(clGetDeviceInfo)
 LOAD_FUNC(clGetProgramBuildInfo)
 LOAD_FUNC(clGetEventProfilingInfo)
 LOAD_FUNC(clReleaseEvent)

 #undef LOAD_FUNC

 LogInfo("tokenhash OpenCL: Runtime loaded OK (macOS)");
 return true;
#else
 LogError("tokenhash OpenCL: Not available on this platform");
 s_available.store(false);
 return false;
#endif
}

static std::string GetExeDirectory() {
 static std::string dir;
 if (!dir.empty()) return dir;
#ifdef _WIN32
 char path[MAX_PATH] = {0};
 GetModuleFileNameA(NULL, path, MAX_PATH);
 std::string p(path);
 auto last = p.find_last_of("\\/");
 dir = (last != std::string::npos) ? p.substr(0, last) : ".";
#elif defined(__APPLE__)
 char path[4096] = {0};
 uint32_t size = sizeof(path);
 if (_NSGetExecutablePath(path, &size) == 0) {
 std::string p(path);
 auto last = p.find_last_of("/");
 dir = (last != std::string::npos) ? p.substr(0, last) : ".";
 } else {
 dir = ".";
 }
#else
 char path[4096] = {0};
 ssize_t len = readlink("/proc/self/exe", path, sizeof(path) - 1);
 if (len > 0) {
 path[len] = 0;
 std::string p(path);
 auto last = p.find_last_of("/");
 dir = (last != std::string::npos) ? p.substr(0, last) : ".";
 } else {
 dir = ".";
 }
#endif
 return dir;
}

static std::string GetTkncHashKernelSource() {
 static std::string cached_source;
 if (!cached_source.empty()) return cached_source;

 // A2: Read kernel from exe's own directory (not CWD)
 // This allows users to customize/replace the kernel without recompiling
 std::string cl_path = GetExeDirectory() + "\\tokenhash.cl";
#ifdef __linux__
 cl_path = GetExeDirectory() + "/tokenhash.cl";
#endif

 std::ifstream f(cl_path, std::ios::binary);
 if (f.is_open()) {
 std::ostringstream ss;
 ss << f.rdbuf();
 cached_source = ss.str();
 LogInfo("tokenhash OpenCL: Loaded kernel from %s (%zu bytes)", cl_path.c_str(), cached_source.size());
 return cached_source;
 }

 // Fallback: use embedded kernel string (zero external dependency)
 // tokenhash_cl.h is always included (compile-time generated by CMake),
 // so TOKENHASH_CL_KERNEL is always available as a static const char[].
 LogInfo("tokenhash OpenCL: Using embedded kernel (%zu bytes, external .cl not found)", TOKENHASH_CL_KERNEL_SIZE);
 cached_source = TOKENHASH_CL_KERNEL;
 return cached_source;
}

// InitOpenCLDevice: enumerate and initialize all GPU candidates as GPUWorkers.
bool OpenCLMiner::InitOpenCLDevice() {
 cl_uint numPlatforms = 0;
 cl_int err = pfn_clGetPlatformIDs(0, nullptr, &numPlatforms);
 if (err != CL_SUCCESS || numPlatforms == 0) {
 LogWarning("TokenHash: No OpenCL platforms found");
 return false;
 }
 LogInfo("TokenHash: Found %u OpenCL platform(s)", numPlatforms);

 std::vector<cl_platform_id> platforms(numPlatforms);
 err = pfn_clGetPlatformIDs(numPlatforms, platforms.data(), nullptr);
 if (err != CL_SUCCESS) return false;

 // Enumerate ALL GPU devices across all platforms
 struct GPUCandidate {
 cl_device_id device;
 cl_platform_id platform;
 std::string name;
 cl_ulong global_mem;
 cl_uint cu_count;
 };
 std::vector<GPUCandidate> candidates;

 for (cl_uint p = 0; p < numPlatforms; p++) {
 char platName[128] = {0}, platVendor[128] = {0};
 pfn_clGetPlatformInfo(platforms[p], 0x402, sizeof(platName), platName, nullptr);
 pfn_clGetPlatformInfo(platforms[p], 0x403, sizeof(platVendor), platVendor, nullptr);

 cl_uint numAllDevices = 0;
#ifdef _WIN32
 err = seh_call_clGetDeviceIDs(platforms[p], CL_DEVICE_TYPE_ALL, 0, nullptr, &numAllDevices);
 if (s_seh_exception_occurred) continue;
#else
 err = pfn_clGetDeviceIDs(platforms[p], CL_DEVICE_TYPE_ALL, 0, nullptr, &numAllDevices);
#endif
 if (err != CL_SUCCESS || numAllDevices == 0) continue;

 std::vector<cl_device_id> allDevices(numAllDevices);
#ifdef _WIN32
 err = seh_call_clGetDeviceIDs(platforms[p], CL_DEVICE_TYPE_ALL, numAllDevices, allDevices.data(), nullptr);
 if (s_seh_exception_occurred) continue;
#else
 err = pfn_clGetDeviceIDs(platforms[p], CL_DEVICE_TYPE_ALL, numAllDevices, allDevices.data(), nullptr);
#endif
 if (err != CL_SUCCESS || allDevices.empty()) continue;

 for (cl_uint d = 0; d < numAllDevices; d++) {
 cl_device_type devType = 0;
 pfn_clGetDeviceInfo(allDevices[d], 0x1000, sizeof(devType), &devType, nullptr);
 if ((devType & CL_DEVICE_TYPE_GPU) == 0) continue;

 char devName[256] = {0};
 pfn_clGetDeviceInfo(allDevices[d], 0x102B, sizeof(devName), devName, nullptr);

 cl_ulong global_mem = 0;
#ifdef _WIN32
 seh_call_clGetDeviceInfo(allDevices[d], CL_DEVICE_GLOBAL_MEM_SIZE, sizeof(global_mem), &global_mem, nullptr);
 if (s_seh_exception_occurred) global_mem = 0;
#else
 pfn_clGetDeviceInfo(allDevices[d], CL_DEVICE_GLOBAL_MEM_SIZE, sizeof(global_mem), &global_mem, nullptr);
#endif

 cl_uint cu = 1;
#ifdef _WIN32
 seh_call_clGetDeviceInfo(allDevices[d], CL_DEVICE_MAX_COMPUTE_UNITS, sizeof(cu), &cu, nullptr);
 if (s_seh_exception_occurred) cu = 1;
#else
 pfn_clGetDeviceInfo(allDevices[d], CL_DEVICE_MAX_COMPUTE_UNITS, sizeof(cu), &cu, nullptr);
#endif

 LogInfo("TokenHash: OpenCL GPU candidate: %s | VRAM=%llu MB | CU=%d | Platform=%s",
 devName, (unsigned long long)(global_mem / (1024*1024)), (int)cu, platVendor);
 candidates.push_back({allDevices[d], platforms[p], std::string(devName), global_mem, cu});
 }
 }

 if (candidates.empty()) {
 LogWarning("TokenHash: No usable OpenCL GPU found");
 return false;
 }

 LogInfo("TokenHash: Found %zu GPU candidate(s), initializing all...", candidates.size());

 std::string kernelSource = GetTkncHashKernelSource();
 if (kernelSource.empty()) {
 LogError("TokenHash: GetTkncHashKernelSource returned empty!");
 return false;
 }

 // Initialize each candidate as a separate GPUWorker.
 for (size_t ci = 0; ci < candidates.size(); ci++) {
 const auto& cand = candidates[ci];

 GPUWorker w;
 w.device = cand.device;
 w.platform = cand.platform;
 w.name = cand.name;

 cl_uint cu_count = cand.cu_count;
 size_t wg_size = 64;
#ifdef _WIN32
 seh_call_clGetDeviceInfo(w.device, CL_DEVICE_MAX_WORK_GROUP_SIZE, sizeof(wg_size), &wg_size, nullptr);
 if (s_seh_exception_occurred) wg_size = 64;
#else
 pfn_clGetDeviceInfo(w.device, CL_DEVICE_MAX_WORK_GROUP_SIZE, sizeof(wg_size), &wg_size, nullptr);
#endif
 int worksize = (int)(wg_size / 16); if (worksize > 8) worksize = 8; if (worksize < 1) worksize = 1;
 w.worksize = worksize;

 uint64_t base_threads = (uint64_t)(cu_count * 6 * 8);
 double intensity = 1.0;

 w.max_threads = (uint64_t)((double)base_threads * intensity);
 if (w.max_threads <= 0) w.max_threads = 100;
 w.max_threads = ((w.max_threads + (uint64_t)worksize - 1) / (uint64_t)worksize) * (uint64_t)worksize;
 LogInfo("TokenHash: GPU[%zu]: %s | CU=%d | Threads=%" PRIu64, ci, cand.name.c_str(), (int)cu_count, w.max_threads);

#ifdef _WIN32
 cl_context_properties props[] = { CL_CONTEXT_PLATFORM, (cl_context_properties)cand.platform, 0 };
 w.context = seh_call_clCreateContext(props, 1, &w.device, nullptr, nullptr, &err);
 if (!w.context && err != CL_SUCCESS) w.context = seh_call_clCreateContext(nullptr, 1, &w.device, nullptr, nullptr, &err);
#else
 w.context = pfn_clCreateContext(nullptr, 1, &w.device, nullptr, nullptr, &err);
#endif
 if (err != CL_SUCCESS || !w.context) { LogError("TokenHash: clCreateContext failed for GPU[%zu] (err=%d)", ci, (int)err); continue; }

#ifdef _WIN32
 w.queue = seh_call_clCreateCommandQueue(w.context, w.device, CL_QUEUE_PROFILING_ENABLE, &err);
#else
 w.queue = pfn_clCreateCommandQueue(w.context, w.device, CL_QUEUE_PROFILING_ENABLE, &err);
#endif
 if (err != CL_SUCCESS || !w.queue) { LogError("TokenHash: clCreateCommandQueue failed for GPU[%zu] (err=%d)", ci, (int)err); pfn_clReleaseContext(w.context); continue; }

 const char* srcPtr = kernelSource.c_str(); size_t srcLen = kernelSource.size();
 char build_opts[512];
 snprintf(build_opts, sizeof(build_opts),
 "-DITERATIONS=%" PRIu64 " -DMASK=%" PRIu64 "U -DWORKSIZE=%dU -DCOMP_MODE=%d -DMEMORY=%" PRIu64 "LU -DCN_UNROLL=%d -cl-fp32-correctly-rounded-divide-sqrt",
 TKNCHASH_ITERATIONS, TKNCHASH_MASK, worksize, TKNCHASH_COMP_MODE, TKNCHASH_MEMORY, TKNCHASH_CN_UNROLL);

#ifdef _WIN32
 w.program = seh_call_clCreateProgramWithSource(w.context, 1, &srcPtr, &srcLen, &err);
#else
 w.program = pfn_clCreateProgramWithSource(w.context, 1, &srcPtr, &srcLen, &err);
#endif
 if (!w.program) { LogError("TokenHash: clCreateProgramWithSource failed for GPU[%zu] (err=%d)", ci, (int)err); pfn_clReleaseCommandQueue(w.queue); pfn_clReleaseContext(w.context); continue; }

#ifdef _WIN32
 err = seh_call_clBuildProgram(w.program, 1, &w.device, build_opts);
#else
 err = pfn_clBuildProgram(w.program, 1, &w.device, build_opts, nullptr, nullptr);
#endif
 if (err != CL_SUCCESS) {
 LogError("TokenHash: Build FAILED for GPU[%zu] (err=%d)", ci, (int)err);
 size_t logSize = 0;
 pfn_clGetProgramBuildInfo(w.program, w.device, CL_PROGRAM_BUILD_LOG, 0, nullptr, &logSize);
 if (logSize > 0) {
 std::vector<char> buildLog(logSize + 1, 0);
 pfn_clGetProgramBuildInfo(w.program, w.device, CL_PROGRAM_BUILD_LOG, logSize, buildLog.data(), nullptr);
 LogError("=== OpenCL Build Log (GPU[%zu]) ===\n%s\n=== END LOG ===", ci, buildLog.data());
 }
 pfn_clReleaseProgram(w.program); pfn_clReleaseCommandQueue(w.queue); pfn_clReleaseContext(w.context);
 continue;
 }

 w.kernel_cn0 = pfn_clCreateKernel(w.program, "cn0_cn_gpu", &err);
 w.kernel_cn00 = pfn_clCreateKernel(w.program, "cn00_cn_gpu", &err);
 w.kernel_cn1 = pfn_clCreateKernel(w.program, "cn1_cn_gpu", &err);
 w.kernel_cn2 = pfn_clCreateKernel(w.program, "cn2", &err);
 if (!w.kernel_cn0 || !w.kernel_cn00 || !w.kernel_cn1 || !w.kernel_cn2) {
 LogError("TokenHash: Kernel create failed for GPU[%zu]!", ci);
 if (w.kernel_cn0) { pfn_clReleaseKernel(w.kernel_cn0); }
 if (w.kernel_cn00) { pfn_clReleaseKernel(w.kernel_cn00); }
 if (w.kernel_cn1) { pfn_clReleaseKernel(w.kernel_cn1); }
 if (w.kernel_cn2) { pfn_clReleaseKernel(w.kernel_cn2); }
 pfn_clReleaseProgram(w.program); pfn_clReleaseCommandQueue(w.queue); pfn_clReleaseContext(w.context);
 continue;
 }

 w.input_buf = pfn_clCreateBuffer(w.context, CL_MEM_READ_ONLY, 128, nullptr, &err);
 w.scratchpads_buf = pfn_clCreateBuffer(w.context, CL_MEM_READ_WRITE, TKNCHASH_MEMORY * w.max_threads, nullptr, &err);
 w.states_buf = pfn_clCreateBuffer(w.context, CL_MEM_READ_WRITE, 200 * w.max_threads, nullptr, &err);
 w.output_buf = pfn_clCreateBuffer(w.context, CL_MEM_READ_WRITE, TKNCHASH_NONCE_LEN * 0x100, nullptr, &err);
 if (!w.input_buf || !w.scratchpads_buf || !w.states_buf || !w.output_buf) {
 LogError("TokenHash: Buffer creation failed for GPU[%zu]!", ci);
 if (w.input_buf) { pfn_clReleaseMemObject(w.input_buf); }
 if (w.scratchpads_buf) { pfn_clReleaseMemObject(w.scratchpads_buf); }
 if (w.states_buf) { pfn_clReleaseMemObject(w.states_buf); }
 if (w.output_buf) { pfn_clReleaseMemObject(w.output_buf); }
 pfn_clReleaseKernel(w.kernel_cn0); pfn_clReleaseKernel(w.kernel_cn00); pfn_clReleaseKernel(w.kernel_cn1); pfn_clReleaseKernel(w.kernel_cn2);
 pfn_clReleaseProgram(w.program); pfn_clReleaseCommandQueue(w.queue); pfn_clReleaseContext(w.context);
 continue;
 }

 LogInfo("TokenHash: GPU[%zu] ready: %s (%" PRIu64 " threads)", ci, cand.name.c_str(), w.max_threads);
 s_workers.push_back(std::move(w));
 }

 if (s_workers.empty()) {
 LogWarning("TokenHash: No usable GPU found (all candidates failed to initialize)");
 return false;
 }

 // Build device name string (comma-separated for multi-GPU)
 std::string name_str;
 for (size_t i = 0; i < s_workers.size(); i++) {
 if (i > 0) name_str += " + ";
 name_str += s_workers[i].name;
 }
 s_device_name = name_str;

 LogInfo("TokenHash: %zu GPU(s) initialized: %s", s_workers.size(), s_device_name.c_str());
 return true;
}

bool OpenCLMiner::Initialize() {
 if (s_initialized.load()) return true;

 LogInfo("=== tokenhash GPU Miner Initializing ===");

 if (!LoadOpenCLRuntime()) {
 LogError("TokenHash: Cannot load OpenCL runtime - No usable GPU found for mining");
 exit(1);
 }

 if (!InitOpenCLDevice()) {
 LogError("TokenHash: GPU initialization failed - No usable GPU found");
 exit(1);
 }

 LogInfo("=== tokenhash GPU Ready: %s (%zu GPU(s)) ===", s_device_name.c_str(), s_workers.size());
 s_cpu_mode.store(false);
 s_initialized.store(true);
 s_available.store(true);
 return true;
}

uint32_t OpenCLMiner::MineBlockCPU(const CBlockHeader& header) {
 static int cpu_warned = 0;
 if (!cpu_warned) {
 fprintf(stderr, "TokenHash: Using CPU TokenHash mining (cn_v4_hash_t, %d threads)\n", CPU_MINER_THREADS);
 cpu_warned = 1;
 }

 arith_uint256 target;
 target.SetCompact(header.nBits);

 s_block_found.store(false);
 s_found_nonce.store(0);

 auto worker_fn = [&](int thread_id) {
 cn_v4_hash_t ctx;
 uint8_t hash_result[32];

 while (!s_block_found.load()) {
 uint32_t my_nonce = s_cpu_next_nonce.fetch_add(1);
 if (my_nonce < header.nNonce + 1) my_nonce = header.nNonce + 1;
 if (my_nonce == 0 || my_nonce >= UINT32_MAX - 10000) break;

 CBlockHeader tryHeader = header;
 tryHeader.nNonce = my_nonce;

 ctx.hash(&tryHeader, sizeof(CBlockHeader), hash_result);
 s_total_hashes.fetch_add(1);

 uint256 resultHash;
 memcpy(resultHash.begin(), hash_result, 32);

 if (UintToArith256(resultHash) <= target) {
 s_block_found.store(true);
 s_found_nonce.store(my_nonce);
 return;
 }
 }
 };

 std::vector<std::thread> workers;
 workers.reserve(CPU_MINER_THREADS);
 for (int t = 0; t < CPU_MINER_THREADS; t++) {
 workers.emplace_back(worker_fn, t);
 }
 for (auto& w : workers) {
 if (w.joinable()) w.join();
 }

 if (s_block_found.load()) {
 uint32_t nonce = s_found_nonce.load();
 s_cpu_next_nonce.store(nonce + 1);
 return nonce;
 }

 return 0;
}

// MineBlockGPU: distribute nonces across all GPU workers.
uint32_t OpenCLMiner::MineBlockGPU(const CBlockHeader& header) {
 if (!s_initialized.load() || s_cpu_mode.load() || s_workers.empty()) {
 fprintf(stderr, "\nFATAL: GPU not available for mining.\n");
 fprintf(stderr, "A3: GPU mining required but GPU is not initialized. Exiting.\n\n");
 exit(1);
 }

 cl_int err;

 uint8_t input_data[128] = {0};
 {
 memcpy(input_data, &header, sizeof(CBlockHeader));
 input_data[sizeof(CBlockHeader)] = 0x01;
 }

 arith_uint256 target;
 target.SetCompact(header.nBits);
 cl_ulong target_u64 = target.GetLow64();

 // GPU kernel compares State[0] (first 8 bytes of hash) as big-endian uint64
 // against Target. State[0] holds the HIGH 64 bits of the 256-bit hash.
 if (target_u64 == 0 && target != arith_uint256()) {
 arith_uint256 hi = target >> 192;
 target_u64 = hi.GetLow64();
 }

 uint32_t start_nonce_base = s_cpu_next_nonce.load();

 // ---- Phase 1: Set up job on each worker (if input changed) ----
 for (size_t wi = 0; wi < s_workers.size(); wi++) {
 GPUWorker& w = s_workers[wi];

 bool input_changed = (memcmp(input_data, w.last_input_data, 128) != 0);
 bool job_need_set = !w.job_set || input_changed || (target_u64 != w.job_target_u64);

 if (job_need_set) {
 w.job_num_threads = (uint32_t)w.max_threads;
 w.job_target_u64 = target_u64;
 memcpy(w.last_input_data, input_data, 128);

 err = pfn_clEnqueueWriteBuffer(w.queue, w.input_buf, CL_TRUE, 0, 128, input_data, 0, nullptr, nullptr);
 if (err != CL_SUCCESS) { LogWarning("TokenHash: GPU[%zu] write input failed", wi); continue; }

 pfn_clSetKernelArg(w.kernel_cn0, 0, sizeof(cl_mem), &w.input_buf);
 pfn_clSetKernelArg(w.kernel_cn0, 1, sizeof(cl_mem), &w.scratchpads_buf);
 pfn_clSetKernelArg(w.kernel_cn0, 2, sizeof(cl_mem), &w.states_buf);
 pfn_clSetKernelArg(w.kernel_cn0, 3, sizeof(uint32_t), &w.job_num_threads);
 pfn_clSetKernelArg(w.kernel_cn0, 4, sizeof(cl_ulong), &s_extra_nonce);
 pfn_clSetKernelArg(w.kernel_cn00, 0, sizeof(cl_mem), &w.scratchpads_buf);
 pfn_clSetKernelArg(w.kernel_cn00, 1, sizeof(cl_mem), &w.states_buf);
 pfn_clSetKernelArg(w.kernel_cn1, 0, sizeof(cl_mem), &w.scratchpads_buf);
 pfn_clSetKernelArg(w.kernel_cn1, 1, sizeof(cl_mem), &w.states_buf);
 pfn_clSetKernelArg(w.kernel_cn1, 2, sizeof(uint32_t), &w.job_num_threads);
 pfn_clSetKernelArg(w.kernel_cn2, 0, sizeof(cl_mem), &w.scratchpads_buf);
 pfn_clSetKernelArg(w.kernel_cn2, 1, sizeof(cl_mem), &w.states_buf);
 pfn_clSetKernelArg(w.kernel_cn2, 2, sizeof(cl_mem), &w.output_buf);
 pfn_clSetKernelArg(w.kernel_cn2, 3, sizeof(cl_ulong), &w.job_target_u64);
 pfn_clSetKernelArg(w.kernel_cn2, 4, sizeof(uint32_t), &w.job_num_threads);

 w.job_set = true;
 w.kernel_args_set = true;
 }

 // Clear output result counter
 uint32_t zero = 0;
 pfn_clEnqueueWriteBuffer(w.queue, w.output_buf, CL_FALSE,
 TKNCHASH_NONCE_LEN * 0xFF, sizeof(uint32_t), &zero, 0, nullptr, nullptr);
 }

 // ---- Phase 2: Launch kernels on each worker with distributed nonce ranges ----
 auto gpu_start = std::chrono::high_resolution_clock::now();

 // Accumulate profiling data across all workers
 int64_t total_profiled_busy_ns = 0;

 for (size_t wi = 0; wi < s_workers.size(); wi++) {
 GPUWorker& w = s_workers[wi];
 if (!w.kernel_cn0 || !w.queue) continue;

 // Each worker gets a contiguous nonce range starting from start_nonce_base + wi * w.max_threads
 uint64_t worker_start_nonce = (uint64_t)start_nonce_base + (uint64_t)wi * w.max_threads;

 size_t g_thd = w.max_threads;
 size_t w_size = TKNCHASH_WORKSIZE;
 if (g_thd % w_size != 0) {
 g_thd = ((g_thd + w_size - 1) / w_size) * w_size;
 }

 size_t cn0_global[1] = {g_thd};
 size_t cn0_offset[1] = {worker_start_nonce};

 cl_event evt_cn0 = nullptr, evt_cn00 = nullptr, evt_cn1 = nullptr, evt_cn2 = nullptr;
 err = pfn_clEnqueueNDRangeKernel(w.queue, w.kernel_cn0, 1, cn0_offset,
 cn0_global, nullptr, 0, nullptr, &evt_cn0);
 if (err != CL_SUCCESS) { LogWarning("TokenHash: GPU[%zu] cn0 launch failed (err=%d)", wi, err); continue; }

 size_t cn00_global[1] = {g_thd * 64};
 size_t cn00_local[1] = {64};

 err = pfn_clEnqueueNDRangeKernel(w.queue, w.kernel_cn00, 1, nullptr,
 cn00_global, cn00_local, 0, nullptr, &evt_cn00);
 if (err != CL_SUCCESS) { LogWarning("TokenHash: GPU[%zu] cn00 launch failed (err=%d)", wi, err); continue; }

 size_t cn1_global[1] = {g_thd * 16};
 size_t cn1_local[1] = {(size_t)(TKNCHASH_WORKSIZE * 16)};

 err = pfn_clEnqueueNDRangeKernel(w.queue, w.kernel_cn1, 1, nullptr,
 cn1_global, cn1_local, 0, nullptr, &evt_cn1);
 if (err != CL_SUCCESS) { LogWarning("TokenHash: GPU[%zu] cn1 launch failed (err=%d)", wi, err); continue; }

 size_t cn2_global[2] = {8, g_thd};
 size_t cn2_local[2] = {8, (size_t)TKNCHASH_WORKSIZE};
 size_t cn2_offset[2] = {0, worker_start_nonce};

 err = pfn_clEnqueueNDRangeKernel(w.queue, w.kernel_cn2, 2, cn2_offset,
 cn2_global, cn2_local, 0, nullptr, &evt_cn2);
 if (err != CL_SUCCESS) { LogWarning("TokenHash: GPU[%zu] cn2 launch failed (err=%d)", wi, err); continue; }

 // Profile this worker's kernels
 cl_event evts[] = {evt_cn0, evt_cn00, evt_cn1, evt_cn2};
 cl_ulong t_min = 0, t_max = 0;
 for (int i = 0; i < 4; i++) {
 if (!evts[i]) continue;
 cl_ulong ps = 0, pe = 0;
 pfn_clGetEventProfilingInfo(evts[i], CL_PROFILING_COMMAND_START, sizeof(ps), &ps, nullptr);
 pfn_clGetEventProfilingInfo(evts[i], CL_PROFILING_COMMAND_END, sizeof(pe), &pe, nullptr);
 if (ps > 0 && pe > 0) {
 if (t_min == 0 || ps < t_min) t_min = ps;
 if (pe > t_max) t_max = pe;
 }
 pfn_clReleaseEvent(evts[i]);
 }
 if (t_max > t_min) total_profiled_busy_ns += (int64_t)(t_max - t_min);
 }

 // ---- Phase 3: Collect results from each worker ----
 uint32_t found_nonce = 0;
 uint64_t total_hashes_this_round = 0;

 for (size_t wi = 0; wi < s_workers.size(); wi++) {
 GPUWorker& w = s_workers[wi];
 if (!w.queue) continue;

 uint64_t worker_start_nonce = (uint64_t)start_nonce_base + (uint64_t)wi * w.max_threads;

 std::vector<uint32_t> output(TKNCHASH_NONCE_LEN * 0x100);
 err = pfn_clEnqueueReadBuffer(w.queue, w.output_buf, CL_TRUE, 0,
 TKNCHASH_NONCE_LEN * 0x100, output.data(), 0, nullptr, nullptr);
 if (err != CL_SUCCESS) {
 LogWarning("TokenHash: GPU[%zu] read output failed (err=%d)", wi, err);
 continue;
 }

 total_hashes_this_round += w.max_threads;

 uint32_t resultCount = output[0xFF];
 if (resultCount > 0xFF) resultCount = 0xFF;

 if (resultCount > 0 && resultCount <= 0xFF) {
 uint32_t nonce = (uint32_t)((uint64_t)output[0] + worker_start_nonce);
 LogInfo("TokenHash-GPU[%zu]: BLOCK FOUND! nonce=%u (results=%u)", wi, nonce, resultCount);
 if (found_nonce == 0) {
 found_nonce = nonce;
 }
 }
 }

 auto gpu_end = std::chrono::high_resolution_clock::now();
 auto gpu_us = std::chrono::duration_cast<std::chrono::microseconds>(gpu_end - gpu_start).count();

 s_total_hashes.fetch_add(total_hashes_this_round);

 UpdateRealUtilization((int64_t)gpu_us, total_profiled_busy_ns);

 if (found_nonce > 0) {
 s_cpu_next_nonce.store(found_nonce + 1);
 return found_nonce;
 }

 // Advance nonce counter past all workers' ranges
 uint64_t total_threads = 0;
 for (const auto& w : s_workers) total_threads += w.max_threads;
 s_cpu_next_nonce.store((uint32_t)(start_nonce_base + total_threads));
 return 0;
}

void OpenCLMiner::UpdateRealUtilization(int64_t gpu_compute_time_us, int64_t profiled_busy_ns) {
 float pdh_util = RealGPUMiner::GetRealGPULoad();
 if (pdh_util >= 0.0f) {
 s_gpu_utilization.store(pdh_util);
 return;
 }
 static auto last_update_time = std::chrono::high_resolution_clock::now();
 static int64_t total_wall_us = 0;
 static const int window_size_ms = 1000;
 total_wall_us += gpu_compute_time_us;
 auto now = std::chrono::high_resolution_clock::now();
 auto elapsed_us = std::chrono::duration_cast<std::chrono::microseconds>(now - last_update_time).count();
 if (elapsed_us >= window_size_ms * 1000 && elapsed_us > 0) {
 float fallback = (float)((double)total_wall_us / (double)elapsed_us) * 100.0f;
 if (fallback > 100.0f) fallback = 100.0f;
 s_gpu_utilization.store(fallback);
 total_wall_us = 0;
 last_update_time = now;
 }
}

float OpenCLMiner::GetGPUUtilization() {
 if (!s_available.load()) return 0.0f;
 float val = s_gpu_utilization.load();
 static float last_reported = 0.0f;
 if (val > 1.0f) { last_reported = val; return val; }
 return last_reported > 0.0f ? last_reported : 0.0f;
}

float OpenCLMiner::GetGPULoad() {
 return GetGPUUtilization();
}

GPUMemoryInfo OpenCLMiner::GetGPUMemoryInfo() {
 GPUMemoryInfo info;
 if (s_available.load() && !s_workers.empty()) {
 uint64_t total_vram = 0;
 uint64_t used_mem = 0;
 for (const auto& w : s_workers) {
 if (w.device) {
 cl_ulong global_mem_size = 0;
 cl_int err = pfn_clGetDeviceInfo(w.device, CL_DEVICE_GLOBAL_MEM_SIZE, sizeof(cl_ulong), &global_mem_size, nullptr);
 if (err == CL_SUCCESS && global_mem_size > 0) {
 total_vram += global_mem_size / (1024 * 1024);
 used_mem += (TKNCHASH_MEMORY * w.max_threads + 200 * w.max_threads + 1024) / (1024 * 1024);
 }
 }
 }
 info.total = total_vram;
 info.used = used_mem;
 } else {
 info.used = 0; info.total = 0;
 }
 return info;
}

bool OpenCLMiner::IsAvailable() { return s_available.load() && s_initialized.load(); }
std::string OpenCLMiner::GetDeviceInfo() { return s_device_name.empty() ? "tokenhash CPU (cn_v4)" : s_device_name; }
bool OpenCLMiner::IsGPUMiningActive() { return s_initialized.load() && s_available.load() && !s_cpu_mode.load(); }
uint64_t OpenCLMiner::GetTotalHashes() { return s_total_hashes.load(); }

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#endif
