// Copyright (c) The TKN Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit.

#ifndef TKN_CHAINPARAMSSEEDS_H
#define TKN_CHAINPARAMSSEEDS_H
/** List of fixed seed nodes for the TKNC network. AUTOGENERATED by contrib/seeds/generate-seeds.py. Each line contains a BIP155 serialized (networkID, addr, port) tuple. */
static const uint8_t chainparams_seed_main[] = {
    // BIP155 IPv4: network=1, addr_len=4, ip=66.154.101.183, port=9333 (big-endian)
    0x01, 0x04, 0x42, 0x9a, 0x65, 0xb7, 0x24, 0x65,
};

static const uint8_t chainparams_seed_test[] = {
};

static const uint8_t chainparams_seed_testnet4[] = {
};

static const uint8_t chainparams_seed_signet[] = {
};
#endif // TKN_CHAINPARAMSSEEDS_H