// Copyright (c) 2012-present The TKN Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <tknc-build-config.h> // IWYU pragma: keep

#include <clientversion.h>

#include <tinyformat.h>
#include <util/string.h>

#include <string>
#include <vector>

using util::Join;

/** Client name in 'version' message; same for tkncd and tknc-qt to avoid targeted attacks. */
const std::string UA_NAME("TKNC");


#include <tknc-build-info.h>
// <tknc-build-info.h> (generated by cmake/script/GenerateBuildInfo.cmake) contains one of:
//   BUILD_GIT_TAG (tagged) / BUILD_GIT_COMMIT (untagged) / "// No build information available".

// git will expand the next line to "#define GIT_COMMIT_ID ..." inside archives:
//$Format:%n#define GIT_COMMIT_ID "%H"$

#ifdef BUILD_GIT_TAG
    #define BUILD_DESC BUILD_GIT_TAG
    #define BUILD_SUFFIX ""
#else
    #define BUILD_DESC "v" CLIENT_VERSION_STRING
    #if CLIENT_VERSION_IS_RELEASE
        #define BUILD_SUFFIX ""
    #elif defined(BUILD_GIT_COMMIT)
        #define BUILD_SUFFIX "-" BUILD_GIT_COMMIT
    #elif defined(GIT_COMMIT_ID)
        #define BUILD_SUFFIX "-g" GIT_COMMIT_ID
    #else
        #define BUILD_SUFFIX "-unk"
    #endif
#endif

static std::string FormatVersion(int nVersion)
{
    return strprintf("%d.%d.%d", nVersion / 10000, (nVersion / 100) % 100, nVersion % 100);
}

std::string FormatFullVersion()
{
    static const std::string CLIENT_BUILD(BUILD_DESC BUILD_SUFFIX);
    return CLIENT_BUILD;
}

/** Format subversion field per BIP 14 (https://github.com/tknc/bips/blob/master/bip-0014.mediawiki). */
std::string FormatSubVersion(const std::string& name, int nClientVersion, const std::vector<std::string>& comments)
{
    std::string comments_str;
    if (!comments.empty()) comments_str = strprintf("(%s)", Join(comments, "; "));
    return strprintf("/%s:%s%s/", name, FormatVersion(nClientVersion), comments_str);
}
