// Copyright (c) 2009-2010 Satoshi Nakamoto
// Copyright (c) 2009-present The TKN Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef TKN_VALIDATIONINTERFACE_H
#define TKN_VALIDATIONINTERFACE_H

#include <kernel/cs_main.h>
#include <primitives/transaction.h>
#include <sync.h>

#include <cstddef>
#include <cstdint>
#include <functional>
#include <memory>
#include <vector>

namespace kernel {
struct ChainstateRole;
} // namespace kernel
namespace util {
class TaskRunnerInterface;
} // namespace util

class BlockValidationState;
class CBlock;
class CBlockIndex;
struct CBlockLocator;
enum class MemPoolRemovalReason;
struct RemovedMempoolTransactionInfo;
struct NewMempoolTransactionInfo;

/** Implement this to subscribe to events generated in validation and mempool. Each CValidationInterface() subscriber receives event callbacks in the order generated by validation and mempool. Each ValidationInterface() subscriber may assume callbacks effectively run in a single thread with single-threaded memory consistency: for a given ValidationInterface() instantiation, each callback completes before the next is invoked. E.g. when a block is connected, the UpdatedBlockTip() callback may depend on an operation performed in the BlockConnected() callback without explicit synchronization. No ordering should be assumed across ValidationInterface() subscribers. */
class CValidationInterface {
protected:
    /** Protected destructor so instances can only be deleted by derived classes. If that restriction is no longer desired, this should be made public and virtual. */
    ~CValidationInterface() = default;
    /** Notifies listeners when the block chain tip advances. When multiple blocks are connected at once, UpdatedBlockTip is called on the final tip but may not be called on every intermediate tip. If the latter behavior is desired, subscribe to BlockConnected() instead. Called on a background thread. Only called for the active chainstate. */
    virtual void UpdatedBlockTip(const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload) {}
    /** Notifies listeners any time the block chain tip changes, synchronously. */
    virtual void ActiveTipChange(const CBlockIndex& new_tip, bool is_ibd) {};
    /** Notifies listeners of a transaction having been added to mempool. Called on a background thread. */
    virtual void TransactionAddedToMempool(const NewMempoolTransactionInfo& tx, uint64_t mempool_sequence) {}

    /** Notifies listeners of a transaction leaving mempool. Fires for transactions removed from the mempool for: EXPIRY (expired after -mempoolexpiry hours); SIZELIMIT (exceeded -maxmempool MB); REORG; CONFLICT (conflicts with in-block tx); REPLACED (RBF). Does NOT fire for txs removed because included in a block—use MempoolTransactionsRemovedForBlock for that. Txs removed due to conflict with new block fire TransactionRemovedFromMempool *before* BlockConnected. With multiple blocks in one step, ordering may be: TransactionRemovedFromMempool(tx1 from A), TransactionRemovedFromMempool(tx2 from A), TransactionRemovedFromMempool(tx1 from B), TransactionRemovedFromMempool(tx2 from B), BlockConnected(A), BlockConnected(B). Called on a background thread. */
    virtual void TransactionRemovedFromMempool(const CTransactionRef& tx, MemPoolRemovalReason reason, uint64_t mempool_sequence) {}
    /* Notifies listeners of transactions removed from the mempool as a result of new block being connected. MempoolTransactionsRemovedForBlock fires before BlockConnected. Called on a background thread. */
    virtual void MempoolTransactionsRemovedForBlock(const std::vector<RemovedMempoolTransactionInfo>& txs_removed_for_block, unsigned int nBlockHeight) {}
    /** Notifies listeners of a block being connected. Called on a background thread. */
    virtual void BlockConnected(const kernel::ChainstateRole& role, const std::shared_ptr<const CBlock>& block, const CBlockIndex* pindex) {}
    /** Notifies listeners of a block being disconnected. Provides the disconnected block. Called on a background thread. Only called for the active chainstate, since background chainstates should never disconnect blocks. */
    virtual void BlockDisconnected(const std::shared_ptr<const CBlock> &block, const CBlockIndex* pindex) {}
    /** Notifies listeners of the new active block chain on-disk. Prior to this callback, updates are not guaranteed to persist on disk (clients must handle shutdown/restart safety). When this callback is invoked, validation changes by any prior callback are guaranteed to exist on disk and survive a restart, including unclean shutdown. Provides a locator describing the best chain, useful for storing current state in client DBs. Called on a background thread. */
    virtual void ChainStateFlushed(const kernel::ChainstateRole& role, const CBlockLocator& locator) {}
    /** Notifies listeners of a block validation result. If the provided BlockValidationState IsValid, the provided block is guaranteed to be the current best block at the time the callback was generated (not necessarily now). */
    virtual void BlockChecked(const std::shared_ptr<const CBlock>&, const BlockValidationState&) {}
    /** Notifies listeners that a block which builds directly on our current tip has been received and connected to the headers tree, though not validated yet. */
    virtual void NewPoWValidBlock(const CBlockIndex *pindex, const std::shared_ptr<const CBlock>& block) {};
    friend class ValidationSignals;
    friend class ValidationInterfaceTest;
};

class ValidationSignalsImpl;
class ValidationSignals {
private:
    std::unique_ptr<ValidationSignalsImpl> m_internals;

public:
    // The task runner will block validation if it calls its insert method's func argument synchronously. In this class func contains a loop that dispatches a single validation event to all subscribers sequentially.
    explicit ValidationSignals(std::unique_ptr<util::TaskRunnerInterface> task_runner);

    ~ValidationSignals();

    /** Call any remaining callbacks on the calling thread */
    void FlushBackgroundCallbacks();

    size_t CallbacksPending();

    /** Register subscriber */
    void RegisterValidationInterface(CValidationInterface* callbacks);
    /** Unregister subscriber. DEPRECATED. This is not safe to use when the RPC server or main message handler thread is running. */
    void UnregisterValidationInterface(CValidationInterface* callbacks);
    /** Unregister all subscribers */
    void UnregisterAllValidationInterfaces();

    // Alternate registration functions that release a shared_ptr after the last notification is sent. Useful for race-free cleanup since unregistration is nonblocking and can return before the last notification is processed.
    /** Register subscriber */
    void RegisterSharedValidationInterface(std::shared_ptr<CValidationInterface> callbacks);
    /** Unregister subscriber */
    void UnregisterSharedValidationInterface(std::shared_ptr<CValidationInterface> callbacks);

    /** Pushes a function to callback onto the notification queue, guaranteeing any callbacks generated prior to now are finished when the function is called. Be very careful blocking on func to be called if any locks are held—validation interface clients may not be able to make progress as they often wait for things like cs_main, so blocking until func is called with cs_main held will result in a deadlock (that DEBUG_LOCKORDER will miss). */
    void CallFunctionInValidationInterfaceQueue(std::function<void ()> func);

    /** Synonym for: std::promise<void> p; CallFunctionInValidationInterfaceQueue([&p] { p.set_value(); }); p.get_future().wait(); which asserts certain locks are not held. */
    void SyncWithValidationInterfaceQueue() LOCKS_EXCLUDED(cs_main);

    void UpdatedBlockTip(const CBlockIndex *, const CBlockIndex *, bool fInitialDownload);
    void ActiveTipChange(const CBlockIndex&, bool);
    void TransactionAddedToMempool(const NewMempoolTransactionInfo&, uint64_t mempool_sequence);
    void TransactionRemovedFromMempool(const CTransactionRef&, MemPoolRemovalReason, uint64_t mempool_sequence);
    void MempoolTransactionsRemovedForBlock(const std::vector<RemovedMempoolTransactionInfo>&, unsigned int nBlockHeight);
    void BlockConnected(const kernel::ChainstateRole&, std::shared_ptr<const CBlock>, const CBlockIndex* pindex);
    void BlockDisconnected(std::shared_ptr<const CBlock>, const CBlockIndex* pindex);
    void ChainStateFlushed(const kernel::ChainstateRole&, const CBlockLocator&);
    void BlockChecked(const std::shared_ptr<const CBlock>&, const BlockValidationState&);
    void NewPoWValidBlock(const CBlockIndex *, const std::shared_ptr<const CBlock>&);
};

#endif // TKN_VALIDATIONINTERFACE_H
